// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import MapController from "./map_controller"
application.register("map", MapController)

import SportsController from "./sports_controller"
application.register("sports", SportsController)

import RunFiltersController from "./run_filters_controller"
application.register("run-filters", RunFiltersController)

import SurfFiltersController from "./surf_filters_controller"
application.register("surf-filters", SurfFiltersController)
