// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import SpotsMapController from "./spots_map_controller"
application.register("spots-map", SpotsMapController)

import MapController from "./map_controller"
application.register("map", MapController)

import SportsController from "./sports_controller"
application.register("sports", SportsController)

import FiltersController from "./filters_controller"
application.register("filters", FiltersController)

import PlacesController from "./places_controller"
application.register("places", PlacesController)

import ButtonDisableController from "./button_disable_controller"
application.register("button-disable", ButtonDisableController)
